export const LOAD_IDEAS = 'LOAD_IDEAS';
export const LOAD_IDEAS_SUCCESS = 'LOAD_IDEAS_SUCCESS';
export const LOAD_IDEAS_FAILURE = 'LOAD_IDEAS_FAILURE';

export const CREATE_IDEA = 'CREATE_IDEA';
export const CREATE_IDEA_SUCCESS = 'CREATE_IDEA_SUCCESS';
export const CREATE_IDEA_FAILURE = 'CREATE_IDEA_FAILURE';

export const UPDATE_IDEA = 'UPDATE_IDEA';
export const UPDATE_IDEA_SUCCESS = 'UPDATE_IDEA_SUCCESS';
export const UPDATE_IDEA_FAILURE = 'UPDATE_IDEA_FAILURE';

export const RESTORE_IDEA = 'RESTORE_IDEA';
export const RESTORE_IDEA_SUCCESS = 'RESTORE_IDEA_SUCCESS';
export const RESTORE_IDEA_FAILURE = 'RESTORE_IDEA_FAILURE';

export const DELETE_IDEA = 'DELETE_IDEA';
export const DELETE_IDEA_SUCCESS = 'DELETE_IDEA_SUCCESS';
export const DELETE_IDEA_FAILURE = 'DELETE_IDEA_FAILURE';
